language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
before_install:
- npm i nodemon webpack webpack-cli webpack-node-externals babel-loader image-webpack-loader
  file-loader css-loader ignore-loader style-loader babel-core babel-plugin-transform-object-rest-spread
  babel-preset-env babel-preset-react-app
